create database DBBOOKCARD1
GO 
use DBBOOKCARD1

GO
CREATE TABLE LIVRO (
LIVID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
LIVNOME VARCHAR(100),
LIVAUTOR VARCHAR(100)
)
GO
CREATE TABLE CAPITULO(
CAPID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CAPDESCRICAO VARCHAR(100) NOT NULL,
LIVID INT NOT NULL FOREIGN KEY REFERENCES LIVRO(LIVID)
)
GO
CREATE TABLE LISTACARD (
LISID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
LISNOME VARCHAR(100) NOT NULL,
LISOVERVIEW VARCHAR(MAX) NULL,
CAPID int 
FOREIGN KEY (CAPID) REFERENCES CAPITULO(CAPID)

)
GO
CREATE TABLE CARDTEXTO (
CARID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CARTEXTO VARCHAR(MAX) NOT NULL,
LISID int
FOREIGN KEY (LISID) REFERENCES LISTACARD(LISID)
)
GO 
CREATE TABLE PALAVRARELEVANTE ( 
PALID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PALTEXTO VARCHAR(100) NOT NULL,
PALPRIORIDADE INT DEFAULT 1
)
GO
CREATE TABLE CLASSIFICACAOPALAVRA (
CLAID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CLADESCRICAO VARCHAR(100) NOT NULL,
)
GO
CREATE TABLE PALAVRA (	
PALID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PALRELEVANTE INT NOT NULL DEFAULT 0,
 PALPALAVRA VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE PALAVRACARD (
PACID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PALID INT NOT NULL FOREIGN KEY REFERENCES PALAVRA (PALID),
CARID INT NOT NULL FOREIGN KEY REFERENCES CARDTEXTO (CARID),
CLAID INT  NULL FOREIGN KEY REFERENCES CLASSIFICACAOPALAVRA (CLAID)
)


ALTER TABLE livro
ADD LIVAUTOR VARCHAR(100) null
select * from LIVRO

ALTER TABLE CARDTEXTO
ADD CAPID int 
FOREIGN KEY (CAPID) REFERENCES CAPITULO(CAPID)

select * from CARDTEXTO

ALTER TABLE CARDTEXTO
DROP COLUMN CAPID